root: true

env:
  browser: true
  es2020: true

extends:
  - '@cordisjs/eslint-config'
  - 'plugin:vue/vue3-recommended'
  - prettier

parser: vue-eslint-parser
parserOptions:
  parser: '@typescript-eslint/parser'
